version: "3"
services:
  auth:
    image: authentication-server:0.1-SNAPSHOT
    container_name: auth-api
    ports:
      - "3000:9000"
  db:
    image: mongo:latest
    container_name: auth-db
    command: mongod
    ports:
      - "37010:27017"
    volumes:
      - ./mongo-data:/usr/local/var/mongodb
      

# mongorestore -h localhost:37017 -d globeapp ./dump/globeapp
 
 


