version: "3"
services:
  app:
    image: app-server:0.1-SNAPSHOT
    container_name: app-api      
    ports:
      - "3001:9000"
  db:
    image: mongo:latest
    container_name: app-db
    command: mongod
    ports:
      - "37011:27017"
    volumes:
      - ./mongo-data:/usr/local/var/mongodb
      

# mongorestore -h localhost:37017 -d globeapp ./dump/globeapp
 
 


